ModuleRegistrationSystem/urls.py
from django.urls import path
from . import views
from .views import PostListView, PostDetailView, ContactFormView

app_name = 'ModuleRegistrationSystem'

urlpatterns = [
 path('', views.home, name = 'home'),
 path('about', views.about, name = 'about'),
 path('contact/', ContactFormView.as_view(), name = 'contact'),
#  path('courselist', Courselist.as_view(), name = 'courselist'),
 path('modulelist/<int:fk>', PostListView.as_view(), name = 'modules'),
 path('module/<int:pk>', PostDetailView.as_view(), name = 'module-detail'),
 path('register_module/<int:module_id>/', views.register_module, name='register_module'),
 path('unregister_module/<int:module_id>/', views.unregister_module, name='unregister_module'),
]

assignment/urls.py
from django.contrib import admin
from django.urls import path, include
from students import views as student_views
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.contrib.auth.views import PasswordResetConfirmView, PasswordResetDoneView, PasswordResetCompleteView
from django.conf.urls.static import static
from students.views import CustomPasswordResetView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ModuleRegistrationSystem.urls')),
    path('register', student_views.register, name = 'register'),
    path('profile', student_views.profile, name = 'profile'),
    path('login', auth_views.LoginView.as_view(template_name = 'students/login.html'), name = 'login'),
    path('logout', auth_views.LogoutView.as_view(template_name = 'students/logout.html'), name='logout'),
    path('password_reset/', CustomPasswordResetView.as_view(), name='password_reset'),
    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset/done/', PasswordResetDoneView.as_view(), name='password_reset_done'),  
    path('reset/done/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),

    
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

ModuleRegistrationSystem/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User, Group, Permission
from django.urls import reverse

class Module(models.Model):
    name = models.CharField(max_length = 100)
    code = models.PositiveIntegerField()
    credit = models.PositiveIntegerField()
    category = models.CharField(max_length = 100, choices = [('Face-to-Face', 'Face-to-Face'), ('Online', 'Online')])
    description = models.TextField()
    availability = models.CharField(max_length = 100 , choices = [('Open', 'Open'), ('Closed', 'Closed')])
    courses = models.ManyToManyField(Group)
    
    def __str__(self):
        return f'{self.name}'
    def get_absolute_url(self):
        return reverse('ModuleRegistrationSystem:module-detail', kwargs = {'pk': self.pk})
    
class Registration(models.Model):
    student = models.ForeignKey(User, related_name = 'registrations', on_delete = models.CASCADE)
    module = models.ForeignKey(Module, related_name = 'registrations', on_delete = models.CASCADE)
    date_of_registration = models.DateField(default = timezone.now)

ModuleRegistrationSystem/forms.py
from django import forms
from django.core.mail import send_mail


class ContactForm(forms.Form):
    name = forms.CharField(max_length = 50)
    email = forms.EmailField()
    subject = forms.CharField(max_length = 100)
    message = forms.CharField(widget = forms.Textarea)

    def send_mail(self):
        send_mail(self.cleaned_data.get('subject') + ', sent on behalf of ' + self.cleaned_data.get('name'),
        self.cleaned_data.get('message'), 
        self.cleaned_data.get('email'), ['c1007012@hallam.shu.ac.uk'])

ModuleRegistrationSystem/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import user_passes_test, login_required
from .models import Module, Registration
from django.views.generic import ListView, DetailView, FormView
from .forms import ContactForm
from django.core.mail import send_mail
from django. contrib import messages
from django.contrib.auth.models import Group



def home(request):
    daily_course = {'course': Group.objects.all(), 'title' : 'Course List'}
    return render(request, 'ModuleRegistrationSystem/home.html', daily_course)
    

def about(request):
    return render(request, 'ModuleRegistrationSystem/about.html', {'title': 'About Us'})


def course(request):
    daily_course = {'course': Group.objects.all(), 'title': 'Course List'}
    return render(request, 'ModuleRegistrationSystem/coursepage.html', daily_course)

def modulelist(request):
    daily_module = {'module': Module.objects.all(), 'title': 'Modules Registered'}
    return render(request, 'ModuleRegistrationSystem/modulelist.html', daily_module)


class ContactFormView(FormView):
    form_class = ContactForm
    template_name = 'ModuleRegistrationSystem/contact.html'

    def get_context_data(self, **kwargs):
        context = super(ContactFormView, self).get_context_data(**kwargs)
        context.update({'title': 'Contact Us'})
        return context

    def form_valid(self, form):
        form.send_mail()
        messages.success(self.request, 'Successfully sent the enquiry')
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.warning(self.request, 'Unable to send the enquiry')
        return super().form_invalid(form)
    
    def get_success_url(self):
        return self.request.path

class PostListView(ListView):
    paginate_by = 3
    model = Module
    template_name = 'ModuleRegistrationSystem/modulelist.html'
    context_object_name = 'module'
    ordering = ['-name']
    

    def get_context_data(self, **kwargs: any):
        context = super().get_context_data(**kwargs)
        course = Group.objects.get(id = self.kwargs.get('fk'))
        context.update({'course': course, 'modules': course.module_set.all()})

        return context

class PostDetailView(DetailView):
    model = Module

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        registrations = Registration.objects.filter(module = self.object)
        context.update({'title': 'Contact Us', 'registrations': registrations})
        
        return context
    
@login_required
def register_module(request, module_id):
    module = get_object_or_404(Module, id=module_id)
    user_groups = request.user.groups.all()

    existing_registration = Registration.objects.filter(student=request.user, module=module).exists()

    if existing_registration:
        messages.info(request, 'You have already registered for this module')
        return redirect('ModuleRegistrationSystem:module-detail', pk=module_id)

    module_courses = module.courses.all()
    if not any(group in user_groups for group in module_courses):
        messages.error(request, 'It is not possible to register for modules that are outside of your course')
        return redirect('ModuleRegistrationSystem:module-detail', pk=module_id)

    if request.method == 'POST':
        registration = Registration(student=request.user, module=module)
        registration.save()


        messages.success(request, 'You are now registered to this Module')

    return redirect('ModuleRegistrationSystem:module-detail', pk=module_id)

@login_required
def unregister_module(request, module_id):
    module = get_object_or_404(Module, id=module_id)
    user = request.user

    existing_registration = Registration.objects.filter(student=user, module=module).exists()

    if not existing_registration:
        messages.info(request, 'You have not registered for this module')
        return redirect('ModuleRegistrationSystem:module-detail', pk=module_id)

    if request.method == 'POST':
        registration = Registration.objects.filter(student=request.user, module=module).first()

        if registration:
            registration.delete()
            messages.success(request, 'You are now unregistered from this Module')
        else:
            messages.error(request, "Error: Registration not found.")


    return redirect('ModuleRegistrationSystem:module-detail', pk=module_id)



# Create your views here.

ModuleRegistrationSystem/templates/ModuleRegistrationSystem/about.html
{% extends "ModuleRegistrationSystem/base.html" %}
{% block content %}

<body>

    <h1>About Us</h1>

    <b>Sheffield Hallam University</b>

    <p></p>
    Sheffield Hallam University, located in the vibrant city of Sheffield, 
    is a leading institution committed to providing a transformative and inclusive 
    educational experience. With a rich history dating back to 1843, the university
    has evolved into a dynamic and innovative hub for learning, research, and 
    professional development.

    At Sheffield Hallam, we take pride in our dedication to student success, offering a 
    diverse range of undergraduate and postgraduate programs designed to meet the demands 
    of today's rapidly changing world. Our faculty consists of accomplished academics 
    and industry professionals, ensuring that students receive a cutting-edge education 
    that prepares them for real-world challenges.
    
    We embrace a collaborative and forward-thinking approach, fostering an environment 
    where creativity and critical thinking thrive. Our state-of-the-art facilities 
    and strong connections with industry partners provide students with valuable 
    hands-on experience and networking opportunities, enhancing their employability 
    upon graduation
</body>
{% endblock content %}

ModuleRegistrationSystem/templates/ModuleRegistrationSystem/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Module Registration System</title>
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="{% url 'ModuleRegistrationSystem:home' %}">Module Registration System</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav mr-auto">
                        <a class="nav-item nav-link" href="{% url 'ModuleRegistrationSystem:home' %}">Home</a>
                        <a class="nav-item nav-link" href="{% url 'ModuleRegistrationSystem:about' %}">About Us</a>
                        <a class="nav-item nav-link" href="{% url 'ModuleRegistrationSystem:contact' %}">Contact Us</a>
                    </ul>
                    <div class="navbar-nav">                            
                        {% if user.is_authenticated %}
                            <a class="nav-item nav-link" href="{% url 'profile' %}">Profile</a>
                            <a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a>
                        {% else %}
                            <a class="nav-item nav-link" href="{% url 'login' %}">Login</a>
                    <a class="nav-item nav-link" href="{% url 'register' %}">Register</a>
                        {% endif %}
                    </div>      
                </div>
            </div>
        </nav>
        <!-- Page Header-->
        <header class="masthead" style="background-image: url('{% static 'assets/banner.jpg' %}')">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="site-heading">
                            <h1>Module Registration System</h1>
                            <span class="subheading">Django Assignment By Nate Garnett</span>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <div class="row">
            <div class="col-md-8">
                {% if messages %}
                    {% for message in messages %}
                    <div class="alert alert-{{message.tags}}">{{ message }}</div>
                    {% endfor %}
                {% endif %}
            {% block content %}{% endblock %}
            </div>
        <!-- Main Content-->
        <div class="container px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
            </div>
        </div>
        <!-- Footer-->
        <footer class="border-top">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <ul class="list-inline text-center">
                            <li class="list-inline-item">
                                <a href="https://twitter.com/sheffhallamuni?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="https://www.facebook.com/sheffieldhallamuniversity/?locale=en_GB">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="https://github.com/c1007012/assignment1django/tree/main">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                        </ul>
                        <div class="small text-center text-muted fst-italic">Copyright &copy; Your Website 2023</div>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>
    </body>
</html>

ModuleRegistrationSystem/templates/ModuleRegistrationSystem/contact.html
{% extends "ModuleRegistrationSystem/base.html" %}
{% load crispy_forms_tags %}
{% block content %}

<section class="py-5">
    <div class="container px-5">
        <div class="bg-light rounded-3 py-5 px-4 px-md-5 mb-5">
            <div class="text-center mb-5">
                <div class="feature bg-primary bg-gradient text-white rounded-3 mb-3"><i class="bi bi-envelope"></i></div>
                <h1 class="fw-bolder">Module Registration System </h1>
                <p class="lead fw-normal text-muted mb-0">Contact Us!</p>
            </div>
            <div class="row gx-5 justify-content-center">
                <div class="col-lg-8 col-xl-6">
                <div class="content-section">
                    <form method="POST">
                        {% csrf_token %}
                        <form id="contactForm" data-sb-form-api-token="API_TOKEN">
                            <div class="form-floating mb-3">
                                {{ form | crispy }}
                            </div>
                            <div class="d-none" id="submitSuccessMessage">
                                <div class="text-center mb-3">
                                    <br />
                                    <a href="https://startbootstrap.com/solution/contact-forms">https://startbootstrap.com/solution/contact-forms</a>
                                </div>
                            </div>
                            <div class="d-grid"><button class="btn btn-outline-info" type="submit">Submit</button>
                        </form>
{% endblock content %}

ModuleRegistrationSystem/templates/ModuleRegistrationSystem/coursepage.html
{% extends "ModuleRegistrationSystem/base.html" %}
{% block content %}

<body>

    <h1>List of Courses</h1>

{% for course in course %}
<article class="media content-section">
    <div class="media-body">
        <h2><a class="article-title" href="{% url 'ModuleRegistrationSystem:modulelist' %}">{{ course }}</a></h2>
        <small class="text-muted"> Credit: {{ course.credit }}</small>
        <p class="article-content">{{ course.description }}</p>
    </div>
</article>
{% endfor %}


{% endblock content %}

ModuleRegistrationSystem/templates/ModuleRegistrationSystem/home.html
{% extends "ModuleRegistrationSystem/base.html" %}
{% block content %}

<h1>Home</h1>

<h2>List of Courses</h2>

{% for course in course %}
    <div class="col-md-4">
        <p class='text-muted'>
            <ul class="list-group">
                <h2 class="h5"><a class="article-title" href="{% url 'ModuleRegistrationSystem:modules' course.id %}">{{ course }}</a> </h2>
            </ul>
        </p>
    </div>
{% endfor %}
{% endblock content %}

ModuleRegistrationSystem/templates/ModuleRegistrationSystem/module_detail.html
{% extends "ModuleRegistrationSystem/base.html" %}
{% block content %}

<body>

    <h1>Module Details</h1>

    <section class="py-5" id="features">
        <div class="media-body">
            <h2 class="article-title"> Module: {{object.name}}</h2>
            <small class="text-muted"> Credit: {{ module.credit }}</small>
            <p class="article-content">{{ module.description }}</p>

            <form method="post" action="{% url 'ModuleRegistrationSystem:register_module' module.id %}">
                {% csrf_token %}
                <button class="btn btn-primary" type="submit">Register</button>
            </form>
            &nbsp;
            <form method="post" action="{% url 'ModuleRegistrationSystem:unregister_module' module.id %}">
                {% csrf_token %}
                <button class="btn btn-primary" type="submit">Unregister</button>
            </form>
        </div>
    </section>

    <h2><p class="article-content">Registered Students: </p>  </h2>

    {% for registration in registrations %}
    <section class="py-5" id="features">
        <div class="container px-5 my-5">
            <div class="row gx-5">
                <div class="col-lg-8">
                    <div class="row gx-5 row-cols-1 row-cols-md-2">
                        <div class="col mb-5 h-100">
                            <div class="feature bg-primary bg-gradient text-white rounded-3 mb-3"><i class="bi bi-collection"></i></div>
                            <p><img class="rounded-circle article-img" src="{{user.profile.image.url}}"></p>
                            <h2 class="h5"><a class="article-title" href="{% url 'profile' %}">{{ registration.student }}</a></h2>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endfor %}
</body>
{% endblock content %}

ModuleRegistrationSystem/templates/ModuleRegistrationSystem/module_form.html
{% extends "ModuleRegistrationSystem/base.html" %}
{% load crispy_forms_tags %}
{% block content %}

<div class="content-section">
    <form method="POST">
    {% csrf_token %}
 
<fieldset class="form-group">
    <legend class="border-bottom mb-4">Create New Module</legend>
    {{ form | crispy}}
    </fieldset>

<div class="form-group">
    <button class="btn btn-outline-info" type="submit">Submit</button>
    </div>
    </form>

    </div>
    {% endblock content %}

ModuleRegistrationSystem/templates/ModuleRegistrationSystem/modulelist.html
{% extends "ModuleRegistrationSystem/base.html" %}
{% block content %}

<body>

    <div class="col-lg-4 mb-5 mb-lg-0"><h2 class="fw-bolder mb-0">List of {{ Course }} Modules</h2></div>
{% for module in modules %}
<article class="media content-section">
    <div class="media-body">
        <h2><a class="article-title" href="{% url 'ModuleRegistrationSystem:module-detail' module.id %}">{{ module }}</a></h2>
        <small class="text-muted"> Credit: {{ module.credit }}</small>
        <p class="article-content">{{ module.description }}</p>
    </div>
</article>
</body>
{% endfor %}

{% if is_paginated %}
    {% if page_obj.has_previous %}
    <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
    <a class="btn btn-outline-info mb-4" href="?page={{page_obj.previous_page_number}}">Previous</a>
 {% endif %}
 {% for num in page_obj.paginator.page_range %}
 {% if page_obj.number == num %}
    <a class="btn btn-info mb-4"
    href="?page={{num}}">{{num}}</a>
 {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
    <a class="btn btn-outline-info mb-4" href="?page={{num}}">{{num}}</a>
 {% endif %}
 {% endfor %}
 {% if page_obj.has_next %}
    <a class="btn btn-outline-info mb-4" href="?page={{page_obj.next_page_number}}">Next</a>
    <a class="btn btn-outline-info mb-4" href="?page={{page_obj.paginator.num_pages}}">Last</a>
 {% endif %}
 {% endif %}

{% endblock content %}